# SPDX-FileCopyrightText: 2023-2026 Michael Serajnik <https://github.com/mserajnik>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  shfmt:
    name: shfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install shfmt
        uses: mfinelli/setup-shfmt@v4

      - name: Run shfmt
        run: find . -type f -not -path './.git/*' -not -path './docker/database/docker-entrypoint.sh' -name '*.sh' -print0 | xargs -0 shfmt -d -i 2 -ci

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run shellcheck
        run: find . -type f -not -path './.git/*' -not -path './docker/database/docker-entrypoint.sh' -name '*.sh' -print0 | xargs -0 shellcheck

  hadolint:
    name: hadolint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          recursive: true

  reuse:
    name: REUSE compliance
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run reuse lint
        uses: fsfe/reuse-action@v6
